[package]
name = "cose_sign1_validation_ffi_mst"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
cose_sign1_validation_ffi = { path = "../cose_sign1_validation_ffi" }
cose_sign1_validation = { path = "../cose_sign1_validation" }
cose_sign1_validation_transparent_mst = { path = "../cose_sign1_validation_transparent_mst" }

[dependencies.anyhow]
workspace = true

[dependencies.libc]
version = "0.2"
