[package]
name = "cose_sign1_validation_trust"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
test = false

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
sha2.workspace = true
hex.workspace = true
once_cell.workspace = true
parking_lot.workspace = true
tinycbor.workspace = true
regex.workspace = true

[dev-dependencies]
anyhow.workspace = true
