[package]
name = "cose_sign1_validation_ffi_akv"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
cose_sign1_validation_ffi = { path = "../cose_sign1_validation_ffi" }
cose_sign1_validation_azure_key_vault = { path = "../cose_sign1_validation_azure_key_vault" }

[dependencies.anyhow]
workspace = true

[dependencies.libc]
version = "0.2"

[dev-dependencies]
cose_sign1_validation = { path = "../cose_sign1_validation" }
