[package]
name = "cose_sign1_validation_transparent_mst"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
test = false

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
hex.workspace = true
sha2.workspace = true
ring.workspace = true
tinycbor.workspace = true
once_cell.workspace = true
url.workspace = true
serde.workspace = true
serde_json.workspace = true
base64.workspace = true
ureq.workspace = true

cose_sign1_validation = { path = "../cose_sign1_validation" }
cose_sign1_validation_trust = { path = "../cose_sign1_validation_trust" }
