[package]
name = "cosesign1-common"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
minicbor.workspace = true
thiserror.workspace = true

[dev-dependencies]
minicbor.workspace = true
