[package]
name = "cose_sign1_validation_ffi_certificates"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]
test = false

[dependencies]
cose_sign1_validation_ffi = { path = "../cose_sign1_validation_ffi" }
cose_sign1_validation = { path = "../cose_sign1_validation" }
cose_sign1_validation_certificates = { path = "../cose_sign1_validation_certificates" }

[dependencies.anyhow]
workspace = true

[dependencies.libc]
version = "0.2"

[dev-dependencies]
cose_sign1_validation_ffi_trust = { path = "../cose_sign1_validation_ffi_trust" }
