[package]
name = "cose_sign1_validation_ffi_trust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
cose_sign1_validation_ffi = { path = "../cose_sign1_validation_ffi" }
cose_sign1_validation = { path = "../cose_sign1_validation" }
cose_sign1_validation_trust = { path = "../cose_sign1_validation_trust" }

[dependencies.anyhow]
workspace = true

[dependencies.libc]
version = "0.2"

[dev-dependencies]
tinycbor = { workspace = true }
cose_sign1_validation_test_utils = { path = "../cose_sign1_validation_test_utils" }
