[package]
name = "cose_openssl"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib"]

[features]
pqc = []

[lints.rust]
warnings = "deny"

[dependencies]
hex = "0.4"
openssl-sys = "0.9"
cborrs-nondet = { git  = "https://github.com/project-everest/everparse.git", rev = "7b55c57ef5b71368bc739dabef7e384f74026e41" }
